### ISSUE TITLE
Visbrain ImportError

### ISSUE THREAD

**Issue by mndhub** [EtienneCmb/visbrain#34]
Dear all
I want to run "from visbrain import Sleep", but i have a problem. this is my script:

import visbrain
_from visbrain.gui import Sleep
/anaconda3/lib/python3.7/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
Traceback (most recent call last):

  File "<ipython-input-2-56a0d0d4e9bb>", line 1, in <module>
    from visbrain.gui import Sleep

  File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/__init__.py", line 1, in <module>
    from .brain import Brain  # noqa

  File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/__init__.py", line 2, in <module>
    from .brain import Brain

  File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/brain.py", line 13, in <module>
    from .interface import UiInit, UiElements, BrainShortcuts

  File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/interface/__init__.py", line 2, in <module>
    from .ui_init import UiInit, BrainShortcuts

  File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/interface/ui_init.py", line 9, in <module>
    from PyQt5 import QtWidgets

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: __os_log_default
  Referenced from: /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libSystem.B.dylib
 in /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore_

system information:
OS X Yosemite: 10.10.5

Thank you in advance...

**Comment by EtienneCmb** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/EtienneCmb/visbrain/issues/4 (installing visbrain), https://github.com/EtienneCmb/visbrain/issues/23 (Hardware requirement for Visbrain), https://github.com/EtienneCmb/visbrain/issues/22 (Visbrain in Pythonnet), https://github.com/EtienneCmb/visbrain/issues/21 (Visbrain in IronPython), and https://github.com/EtienneCmb/visbrain/issues/10 (Update and/or redirect links to visbrain modules).

**Comment by mndhub** [comment]
i am using Spyder to run this script. there was no problem in installing visbrain.

**Comment by EtienneCmb** [comment]
Hi @mndhub ,

Can you please try to run :
```python
from visbrain.gui import Sleep
```

**Comment by mndhub** [comment]
Hi EtienneCmb,
I tried "from visbrain.gui import Sleep". 

import visbrain
_from visbrain.gui import Sleep
/anaconda3/lib/python3.7/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
Traceback (most recent call last):

File "", line 1, in 
from visbrain.gui import Sleep

File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/init.py", line 1, in 
from .brain import Brain # noqa

File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/init.py", line 2, in 
from .brain import Brain

File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/brain.py", line 13, in 
from .interface import UiInit, UiElements, BrainShortcuts

File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/interface/init.py", line 2, in 
from .ui_init import UiInit, BrainShortcuts

File "/anaconda3/lib/python3.7/site-packages/visbrain/gui/brain/interface/ui_init.py", line 9, in 
from PyQt5 import QtWidgets

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/PyQt5/QtWidgets.so, 2): Symbol not found: _os_log_default
Referenced from: /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.11)
Expected in: /usr/lib/libSystem.B.dylib
in /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore

**Comment by EtienneCmb** [comment]
I think this is because you have a PyQt version installed using conda. Can you try to install it using pip? `pip install pyqt5`
