### ISSUE TITLE
Brain GUI screenshot issue

### ISSUE THREAD

**Issue by miao-cao** [EtienneCmb/visbrain#56]
Hi visbrain,

I'm preparing figures for publication by saving screenshots (tried both GUI and programming) from Brain GUI. However, I found some shadows on cortical surfaces from saved figures. To be noted, I used Freesurfer pial surface generated from individual's T1 MPRage MR scan. And the Visbrain version I'm using is 0.4.5

An example figure is attached below,
![test](https://user-images.githubusercontent.com/11639120/70873683-e27ba980-2002-11ea-8c24-6d75b6c91a4c.png)

Cheers,
Miao

**Comment by EtienneCmb** [comment]
Hi @miao-cao ,

Yes, I've seen this issue before. From what I've read, it's seems that this is an OpenGL issue for meshes with vertices coordinates that are under 1. Can you try to multiply your vertices by 1000 for example and see if it fixes your issue?

**Comment by GShimmering** [comment]
Same problem encountered here but with the screenshot demo code:
![1_proj_brain](https://user-images.githubusercontent.com/26790848/75701532-ec9e7180-5cee-11ea-88c0-fd94d012f18e.jpg)


Also, this code return an error with following tractback:
Traceback (most recent call last):
  File "D:/brainvis_screenshot.py", line 52, in <module>
    vb = Brain(brain_obj=b_obj, source_obj=s_obj, roi_obj=roi_obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\visbrain\gui\brain\brain.py", line 101, in __init__
    UiInit.__init__(self, bgcolor)  # GUI creation + canvas
  File "C:\ProgramData\Anaconda3\lib\site-packages\visbrain\gui\brain\interface\ui_init.py", line 125, in __init__
    self.setupUi(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\visbrain\gui\brain\interface\gui\brain_gui.py", line 1881, in setupUi
    QtCore.QMetaObject.connectSlotsByName(MainWindow)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

So I comment out the signal-slot connection line, 
    _QtCore.QMetaObject.connectSlotsByName(MainWindow)_, line 1881 of brain_gui.py
and get results of screenshots, but with holes, like the above attached image.

**Comment by EtienneCmb** [comment]
Hi @miao-cao ,

When visualizing the mesh inside the GUI, there's no black holes? This is only happening when exporting?

**Comment by EtienneCmb** [comment]
@GShimmering 

can you give me the vispy version your on :
```python
import vispy
print(vispy.__version__)
```

**Comment by GShimmering** [comment]
@EtienneCmb 
it's '0.6.4'.

**Comment by GShimmering** [comment]
@EtienneCmb 

BTW, I tried visualizing my own ROI obj:
1. holes are observed after exporting
2. no holes in scene.preview()

My roi image is a classification result in MNI space. So a voxel value indicates a class label, i.e., integer 1~N. ROIs are selected via:
_roi_custom.select_roi(list(range(1, N)), unique_color=True, smooth=3)_

**Comment by EtienneCmb** [comment]
I remembered that I had to tweak vispy for exporting in higher resolutions. Probably they improved exporting the canvas since then. Can you please try to downgrade your vispy version. For example :

```bash
pip install -U vispy==0.6.0
```

**Comment by GShimmering** [comment]
@EtienneCmb 
Great, now the holes are gone from the exported images.
![1_proj_brain](https://user-images.githubusercontent.com/26790848/75705272-02fbfb80-5cf6-11ea-9396-268d17af26d7.jpg)

**Comment by EtienneCmb** [comment]
Ok, thanks, so they changed something in vispy and visbrain needs to be updated.

Can you please open an issue ? I'll try to fix it asap

**Comment by GShimmering** [comment]
@EtienneCmb 

https://github.com/EtienneCmb/visbrain/issues/66

**Comment by benelot** [comment]
> ```shell
> pip install -U vispy==0.6.0
> ```

Could we mention this somewhere or make a dependency of visbrain to that specific version? I just looked everywhere for this.

**Comment by Vince-LD** [comment]
Hello,
I am having exactly the same issue as you @miao-cao and @GShimmering. However, downgrading vispy doesn't work (outputs an error). I have been working on this all day and even though it's an old topic, I was wondering if one of you had a working solution because right now I am completely stuck. I'm adding pictures of what screenshots look like. The only thing that improves the situation is lowering the _scale when creating the RoiObj. 
I have the same bug when I try to record an animation. Previews are completely fine though, even with the animation.

![test_screenshot_bugged](https://user-images.githubusercontent.com/65451491/154115651-6e843f42-b1a3-4c29-98d3-6a1269b7ea4c.png)

![test_screenshot](https://user-images.githubusercontent.com/65451491/154115665-246e4d5f-f8a8-4e43-9d3c-a2988a66f407.png)
