### ISSUE TITLE
Sleep gui does not open

### ISSUE THREAD

**Issue by mtantirigama** [EtienneCmb/visbrain#74]
Hi EtienneCmb,
I am trying the 'Load matlab file' example. But when the Sleep gui launches it freezes and does not show anything or respond. I am using JupyterLab  on a windows 10 machine. 
These are installed,
NumPy 1.18.3
SciPy  1.4.1
VisPy 0.6.4
Matplotlib 3.2.1
PyQt5 5.14.2
Pillow 7.1.1
PyOpenGL 3.1.5

When i execute the code this is what i get, 

C:\Users\tantirim\AppData\Roaming\Python\Python37\site-packages\visbrain\gui\sleep\visuals\marker.py:569: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])
File already dowloaded (C:\Users\tantirim\visbrain_data\topo\eegref.npz).
WARNING | Ignored channels for topoplot : EOG1, EOG2, EMG1, EMG2, EMG3, ECG
File already dowloaded (C:\Users\tantirim\visbrain_data\topo\eegref.npz).

Could you please help ?

**Comment by EtienneCmb** [comment]
Hi @mtantirigama ,

Yes, for the moment visbrain is not fully compatible with Jupiter. Try with the scripts instead

**Comment by mtantirigama** [comment]
Hi @EtienneCmb Thank you for getting back to me. I tried using a script, but i get the following error. 

AttributeError: __getattribute__


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\tantirim\untitled0.py", line 29, in <module>
    Sleep(data=raw_data, sf=raw_sf, channels=raw_channels, hypno=raw_hypno).show()

  File "C:\Users\tantirim\AppData\Roaming\Python\Python37\site-packages\visbrain\gui\sleep\sleep.py", line 88, in __init__
    UiInit.__init__(self)

  File "C:\Users\tantirim\AppData\Roaming\Python\Python37\site-packages\visbrain\gui\sleep\interface\ui_init.py", line 26, in __init__
    self.setupUi(self)

  File "C:\Users\tantirim\AppData\Roaming\Python\Python37\site-packages\visbrain\gui\sleep\interface\gui\sleep_gui.py", line 2008, in setupUi
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

SystemError: <built-in function connectSlotsByName> returned a result with an error set

**Comment by stephanakwe** [comment]
I have this same issue
