### ISSUE TITLE
Can't run on Big Sur

### ISSUE THREAD

**Issue by dansamber** [EtienneCmb/visbrain#86]
I'm new to Visbrain and naively tried to run a demo on my new M1 Macbook Air.
I used Anaconda Navigator to create an environment and ran "pip install -U visbrain" from that environment's terminal window. After updates, I typed "from visbrain.gui import Brain" and.... BOOM! (see details below)

I tried multiple versions of python but that didn't make a difference.
I'm guessing that this has to do with Big Sur???

Any suggestions?

Thanks!

Dan
**************************
>>> from visbrain.gui import Brain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/visbrain/gui/__init__.py", line 1, in <module>
    from .brain import Brain  # noqa
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/visbrain/gui/brain/__init__.py", line 2, in <module>
    from .brain import Brain
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/visbrain/gui/brain/brain.py", line 11, in <module>
    import vispy.scene.cameras as viscam
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/site-packages/vispy/ext/cocoapy.py", line 930, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/Users/dan/opt/anaconda3/envs/VisBrain_Dan/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found

**Comment by raphaelvallat** [comment]
Hi @dansamber,

Unfortunately, I'm having the same issue right now, which seems to be related to: https://github.com/vispy/vispy/issues/1885

Just curious, which version of Python are you using?

Thanks
Raphael

**Comment by dansamber** [comment]
Raphael,

I googled around and actually found the same web page you referenced.
I have tried multiple versions of Python but it makes no difference.
Although I admit to being somewhat new to python, I'm a little confused why
this is (apparently) dependent on the OS. I thought that the whole point of
virtual environments was to get away from such things.

Sigh!

Dan

**Comment by EtienneCmb** [comment]
Hi @dansamber ,

> I'm a little confused why this is (apparently) dependent on the OS. I thought that the whole point of virtual environments was to get away from such things. Sigh! Dan

In general you're right however, in that case, vispy (and therefore visbrain) uses OpenGL for the graphic rendering and apparently, Big sur doesn't include OpenGL anymore. See [here](https://stackoverflow.com/questions/63475461/unable-to-import-opengl-gl-in-python-on-macos) for a description and possible workaround
